# Generated by Django 5.1.2 on 2024-12-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('song_img', models.ImageField(upload_to='songsimg')),
                ('audio', models.FileField(upload_to='audio_files/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.section')),
            ],
        ),
    ]
