# Generated by Django 5.1.2 on 2024-12-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_section1_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.section1'),
        ),
    ]
