# Generated by Django 5.1.2 on 2024-12-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_play_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Podc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('pod_img', models.ImageField(upload_to='podimg')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.section2')),
            ],
        ),
    ]
