# Generated by Django 5.1.2 on 2024-12-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_section2_podc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=200)),
                ('date', models.IntegerField()),
                ('heading', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('song_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.podc')),
            ],
        ),
    ]
