# Generated by Django 5.1.2 on 2024-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_podpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podpage',
            old_name='heading',
            new_name='ep_name',
        ),
        migrations.AlterField(
            model_name='podpage',
            name='des',
            field=models.TextField(max_length=200),
        ),
    ]
