# Generated by Django 5.1.2 on 2024-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_heading_podpage_ep_name_alter_podpage_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podpage',
            name='des',
            field=models.TextField(),
        ),
    ]
