# Generated by Django 5.1.2 on 2024-12-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_podpage_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albumpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('date', models.IntegerField()),
                ('artist_name', models.CharField(max_length=200)),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.play')),
            ],
        ),
    ]
